config/routes.rb
Estoque::Application.routes.draw do
  resources :pagamentos

   root :to => "home#index"

end

app/models/pagamento.rb
class Pagamento < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  # GET /pagamentos
  # GET /pagamentos.xml
  def index
    @pagamentos = Pagamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pagamentos }
    end
  end

  # GET /pagamentos/1
  # GET /pagamentos/1.xml
  def show
    @pagamento = Pagamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pagamento }
    end
  end

  # GET /pagamentos/new
  # GET /pagamentos/new.xml
  def new
    @pagamento = Pagamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pagamento }
    end
  end

  # GET /pagamentos/1/edit
  def edit
    @pagamento = Pagamento.find(params[:id])
  end

  # POST /pagamentos
  # POST /pagamentos.xml
  def create
    @pagamento = Pagamento.new(params[:pagamento])

    respond_to do |format|
      if @pagamento.save
        format.html { redirect_to(@pagamento, :notice => 'Pagamento was successfully created.') }
        format.xml  { render :xml => @pagamento, :status => :created, :location => @pagamento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pagamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pagamentos/1
  # PUT /pagamentos/1.xml
  def update
    @pagamento = Pagamento.find(params[:id])

    respond_to do |format|
      if @pagamento.update_attributes(params[:pagamento])
        format.html { redirect_to(@pagamento, :notice => 'Pagamento was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pagamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pagamentos/1
  # DELETE /pagamentos/1.xml
  def destroy
    @pagamento = Pagamento.find(params[:id])
    @pagamento.destroy

    respond_to do |format|
      format.html { redirect_to(pagamentos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pagamentos_helper.rb
module PagamentosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Estoque</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pagamentos/_form.html.erb
<%= form_for(@pagamento) do |f| %>
  <% if @pagamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pagamento.errors.count, "error") %> prohibited this pagamento from being saved:</h2>

      <ul>
      <% @pagamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pagamentos/edit.html.erb
<h1>Editing pagamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @pagamento %> |
<%= link_to 'Back', pagamentos_path %>

app/views/pagamentos/index.html.erb
<h1>Listing pagamentos</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Tipo</th>
    <th>Valor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pagamentos.each do |pagamento| %>
  <tr>
    <td><%= pagamento.id %></td>
    <td><%= pagamento.tipo %></td>
    <td><%= pagamento.valor %></td>
    <td><%= link_to 'Show', pagamento %></td>
    <td><%= link_to 'Edit', edit_pagamento_path(pagamento) %></td>
    <td><%= link_to 'Destroy', pagamento, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pagamento', new_pagamento_path %>

app/views/pagamentos/new.html.erb
<h1>New pagamento</h1>

<%= render 'form' %>

<%= link_to 'Back', pagamentos_path %>

app/views/pagamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @pagamento.id %>
</p>

<p>
  <b>Tipo:</b>
  <%= @pagamento.tipo %>
</p>

<p>
  <b>Valor:</b>
  <%= @pagamento.valor %>
</p>


<%= link_to 'Edit', edit_pagamento_path(@pagamento) %> |
<%= link_to 'Back', pagamentos_path %>